### ISSUE TITLE
hello

### ISSUE THREAD

**Issue by ALAWIII** [pavles6/one-dark-darkened#1]
the darkened version is pretty good,
can you make the keywords of rust language italic and a brighter purple color?
the type annotation must be yellow-gold !!
like this :

![image](https://github.com/user-attachments/assets/ce5fc21c-da10-4c6f-ac0c-e41f756b307b)

**Comment by pavles6** [comment]
Hi, I'm glad you're liking it. However, my aim is to provide theme that is consistent with the `One Dark` theme that zed comes with by default. Purpose of this theme is to just enhance the default contrast which is for some of zed' users pretty low. 
> brighter purple color?
> the type annotation must be yellow-gold !!

Currently, I am not aware of the language-specific color theme customization, colors are being assigned for the different types of tree-sitter tokens that are language-agnostic. So even if I would want to implement your  suggestions for different colors for rust code, that would be impossible at the moment. 

> can you make the keywords of rust language italic

There is a feature to make certain parts of the code appear in different font style/weight, but as I said, since that is not the way default `One Dark` theme works, I have no incentive to make change.

Feel free to copy `one-dark-darkened.json` contents and place it in `~/.zed/themes` directory, and you can adjust it to your preferences. https://zed.dev/docs/themes#local-themes
